export const ECONOMY_PROFILES = {
  casual: {
    label: 'Casual',
    fixedCostMultiplier: 0.8,
    variableCostMultiplier: 0.82,
    maintenanceMultiplier: 0.85,
    staffMultiplier: 0.9,
    taxRateMultiplier: 0.75,
    monthlyRentMultiplier: 0.8,
    demandModifier: 1,
    debtInterestMultiplier: 0.7,
    rescueThreshold: -320,
    rescueTargetCash: 220,
    rescueInterestMultiplier: 1.04,
    rewardMultiplier: 1.2,
    safeCashBuffer: 200,
  },
  normal: {
    label: 'Normal',
    fixedCostMultiplier: 1,
    variableCostMultiplier: 1,
    maintenanceMultiplier: 1,
    staffMultiplier: 1,
    taxRateMultiplier: 1,
    monthlyRentMultiplier: 1,
    demandModifier: 0,
    debtInterestMultiplier: 1,
    rescueThreshold: -200,
    rescueTargetCash: 100,
    rescueInterestMultiplier: 1.18,
    rewardMultiplier: 1,
    safeCashBuffer: 300,
  },
  hardcore: {
    label: 'Hardcore',
    fixedCostMultiplier: 1.28,
    variableCostMultiplier: 1.22,
    maintenanceMultiplier: 1.25,
    staffMultiplier: 1.2,
    taxRateMultiplier: 1.25,
    monthlyRentMultiplier: 1.2,
    demandModifier: -1,
    debtInterestMultiplier: 1.45,
    rescueThreshold: -120,
    rescueTargetCash: 70,
    rescueInterestMultiplier: 1.38,
    rewardMultiplier: 0.85,
    safeCashBuffer: 450,
  },
};
